// <copyright file="Metadata.cs" company="DeltaForth Contributors">
// Copyright © 1997-2011 Valer BOCAN
// Copyright © 2018 Neil McNeight
// All rights reserved.
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
// </copyright>

using System.Collections.Generic;

namespace DeltaForth.Collections
{
    /// <summary>
    /// Metadata generated by the Forth syntactic analyzer and consumed by the code generator.
    /// </summary>
    public class Metadata
    {
        /// <summary>
        /// Gets or sets library name (as declared by the LIBRARY keyword).
        /// </summary>
        public string LibraryName { get; set; }

        /// <summary>
        /// Gets or sets global constants.
        /// </summary>
        public List<GlobalConstant> GlobalConstants { get; set; }

        /// <summary>
        /// Gets or sets global variables.
        /// </summary>
        public List<GlobalVariable> GlobalVariables { get; set; }

        /// <summary>
        /// Gets or sets local variables.
        /// </summary>
        public List<LocalVariable> LocalVariables { get; set; }

        /// <summary>
        /// Gets or sets words.
        /// </summary>
        public List<Word> Words { get; set; }

        /// <summary>
        /// Gets or sets external words.
        /// </summary>
        public List<ExternalWord> ExternalWords { get; set; }
    }
}
